image:
  repository: 327512370966.dkr.ecr.us-east-1.amazonaws.com/vih-nlp
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  port: 8000

ingress:
  enabled: false
  host: ""
  certificateArn: ""
